# Generated by Django 3.0.7 on 2020-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdToName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CorporationName',
        ),
    ]
